name: Python Package CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Check API Key
      run: |
        if [ -z "$CLOUDSMITH_API_KEY" ]; then echo "API Key is not set"; else echo "API Key is set"; fi
      env:
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

    - name: Upload to Cloudsmith
      run: |
        pip install cloudsmith-cli
        cloudsmith push python interview-indranarayan-chaudhu/interview-indranarayan-chaudhuri dist/*.whl
      env:
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
